### PR TITLE
I have done JavaScript for reptiles page. Need your feedback. 

### PR DESCRIPTION
**Pull request by sabawaheed27**

### CODE REVIEW

**Comment by yevhenii-kapustian** [comment]
again) u cant immediately merge code into the main branch without a test, first send it for testing in the develop branch)))

**Review by andrewkalumba — COMMENTED** [review]
looks so good

**Review by yevhenii-kapustian — COMMENTED** [review]
to develop branch

**Review by Maatala — APPROVED** [review]
LGTM

**Pull request closed without merging**
