### PR TITLE
Andrew homepage

### PR DESCRIPTION
**Pull request by andrewkalumba**
Review and see if it works for us all

### CODE REVIEW

**Comment by SSSpac** [comment]
I like the design for the sidebar, but when i switch to ipad mini or iphone view the sidebar is gone ? can one more person check and see if they can find the sidebar in smaller screens before we merge ?

**Review by Maatala — COMMENTED** [review]
Yes, the sidebar disapears in iphone 12 or something else. maybe if your put display: block in body it works. and I dont know, you maybe need one more media query for max-width 480px and not only 768px.

**Comment by andrewkalumba** [comment]
i will look at it and see what to do

**Review by sabawaheed27 — COMMENTED** [review]
I cloned it , can't see anything. Please help me

**Pull request closed without merging**
